id: check-sync-flow
namespace: myteam
description: Save and Execute the flow

labels:
  env: prod
  project: debug

inputs:
  - id: payload
    type: JSON
    defaults: |
      [{"name": "kestra", "rating": "best in class"}]

tasks:
  - id: send_data
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{ inputs.payload }}"

  - id: print_status
    type: io.kestra.core.tasks.log.Log
    message: hello on {{ outputs.send_data.headers.date | first }}

triggers:
  - id: daily
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"